# Generated by Django 4.1.3 on 2025-03-15 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_card_id',
            field=models.PositiveIntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='current_question_id',
            field=models.PositiveIntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='revise_card_id',
            field=models.PositiveIntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(choices=[(1, 'choice'), (2, 'short_answer'), (3, 'code')]),
        ),
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('last_access', models.DateTimeField()),
                ('last_score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
