# Generated by Django 5.2.4 on 2025-07-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_prerequisites_card_title_learningrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_card_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_question_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='revise_card_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
