# Generated by Django 5.2.4 on 2025-07-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_question_options_user_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_learned_cards', models.PositiveIntegerField(default=0)),
                ('total_mastered_cards', models.PositiveIntegerField(default=0)),
                ('daily_goal', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='learningrecord',
            old_name='completion_time',
            new_name='first_learned',
        ),
        migrations.RenameField(
            model_name='learningrecord',
            old_name='attempts',
            new_name='practice_attempts',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='completed',
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='mastered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='practice_correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='queue',
            field=models.CharField(choices=[('learning', '学习队列'), ('practice', '练习队列'), ('review', '复习队列')], default='learning', max_length=20),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='review_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='status',
            field=models.CharField(choices=[('not_learned', '未学过'), ('learning', '学过但未完全掌握'), ('mastered', '完全掌握')], default='not_learned', max_length=20),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='code_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='answerrecord',
            index=models.Index(fields=['user', 'question'], name='cards_answe_user_id_9deb06_idx'),
        ),
        migrations.AddIndex(
            model_name='answerrecord',
            index=models.Index(fields=['is_correct'], name='cards_answe_is_corr_99397a_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['user', 'queue'], name='cards_learn_user_id_ce5399_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['next_review_date'], name='cards_learn_next_re_84936e_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['status'], name='cards_learn_status_a37d0e_idx'),
        ),
        migrations.AddField(
            model_name='smartscheduler',
            name='current_learning_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learning_users', to='cards.card'),
        ),
        migrations.AddField(
            model_name='smartscheduler',
            name='current_practice_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_practice_users', to='cards.card'),
        ),
        migrations.AddField(
            model_name='smartscheduler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
